// --- Custom icon set (Style A) -----------------------------------
// Monochrome inline SVGs that replace the app's text glyphs and the
// wind arrows. viewBox 0 0 24 24, sized to ~1em by CSS, coloured by
// currentColor so each icon inherits its context: the block's
// luminance-picked contrast colour, gold for now/saved, grey for
// chrome. One source of truth; keys map to the render slots below.
// Full reference: "Weather PWA/Maybe Rain Icons.md". A few marks
// (snow, solar, sunrise, sunset) are kept for features not built yet
// and need no wiring today. mrIcon(key) returns the SVG or ''.
const MR_ICON = {
    storm: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M13.5 2.5 9 11.5 15 11.5 10.5 20.5\"/></svg>",
    fog: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M4.5 8h12\"/><path vector-effect=\"non-scaling-stroke\" d=\"M6.5 12h13\"/><path vector-effect=\"non-scaling-stroke\" d=\"M4.5 16h11\"/></svg>",
    freeze: "<svg viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M12 3C14.3 7 15.6 8.6 15.6 10.8A3.6 3.6 0 1 1 8.4 10.8C8.4 8.6 9.7 7 12 3Z\"/><g fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M7 17.5h10\"/><path vector-effect=\"non-scaling-stroke\" d=\"M9 17.5v3\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 17.5v3.5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M15 17.5v3\"/></g></svg>",
    snow: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 3.5V20.5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M4.6 7.75 19.4 16.25\"/><path vector-effect=\"non-scaling-stroke\" d=\"M19.4 7.75 4.6 16.25\"/></svg>",
    rainwarn: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 3 21 19.5H3Z\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 9v5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 16.8v.01\"/></svg>",
    heat: "<svg viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"17.6\" r=\"3.4\" fill=\"currentColor\"/><g fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 5V14.6\"/><path vector-effect=\"non-scaling-stroke\" d=\"M14.6 7.8h2.2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M14.6 10.8h2.2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M14.6 13.8h2.2\"/></g></svg>",
    uv: "<svg viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"4.8\" fill=\"currentColor\"/><g fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 3.4V5.8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 18.2V20.6\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3.4 12H5.8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M18.2 12H20.6\"/><path vector-effect=\"non-scaling-stroke\" d=\"M6.1 6.1 7.8 7.8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M16.2 16.2 17.9 17.9\"/><path vector-effect=\"non-scaling-stroke\" d=\"M17.9 6.1 16.2 7.8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M6.1 17.9 7.8 16.2\"/></g></svg>",
    new: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"7\"/></svg>",
    first: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"7\"/><path d=\"M12 5A7 7 0 0 1 12 19Z\" fill=\"currentColor\" stroke=\"none\"/></svg>",
    full: "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\"><circle cx=\"12\" cy=\"12\" r=\"7\"/></svg>",
    last: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"7\"/><path d=\"M12 5A7 7 0 0 0 12 19Z\" fill=\"currentColor\" stroke=\"none\"/></svg>",
    lunar: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"3.2\" fill=\"currentColor\" stroke=\"none\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"7\"/></svg>",
    solar: "<svg viewBox=\"0 0 24 24\"><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M12 7.2A4.8 4.8 0 1 0 12 16.8 4.8 4.8 0 1 0 12 7.2ZM15.5 4.3A4.2 4.2 0 1 0 15.5 12.7 4.2 4.2 0 1 0 15.5 4.3Z\"/><g fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 3.4V5.8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 18.2V20.6\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3.4 12H5.8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M6.1 6.1 7.8 7.8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M16.2 16.2 17.9 17.9\"/><path vector-effect=\"non-scaling-stroke\" d=\"M6.1 17.9 7.8 16.2\"/></g></svg>",
    sunrise: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 19A4 4 0 0 1 16 19Z\" fill=\"currentColor\" stroke=\"none\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3 19h18\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 13.5V3.2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M8 7.2 12 3.2 16 7.2\"/></svg>",
    sunset: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 19A4 4 0 0 1 16 19Z\" fill=\"currentColor\" stroke=\"none\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3 19h18\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 3.2V13.5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M8 9.5 12 13.5 16 9.5\"/></svg>",
    wind: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 3.5V20.5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M6.5 10 12 3.5 17.5 10\"/></svg>",
    gear: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"5.6\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"2.2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\" transform=\"rotate(45 12 12)\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\" transform=\"rotate(90 12 12)\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\" transform=\"rotate(135 12 12)\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\" transform=\"rotate(180 12 12)\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\" transform=\"rotate(225 12 12)\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\" transform=\"rotate(270 12 12)\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6.4V4.2\" transform=\"rotate(315 12 12)\"/></svg>",
    star: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 5V19\"/><path vector-effect=\"non-scaling-stroke\" d=\"M5 12H19\"/></svg>",
    refresh: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M18.6 7.4A7 7 0 1 0 19.4 13\"/><path vector-effect=\"non-scaling-stroke\" d=\"M18.6 3V7.6H14\"/></svg>",
    locate: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"6\"/><circle cx=\"12\" cy=\"12\" r=\"2\" fill=\"currentColor\" stroke=\"none\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 2.4V5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 19V21.6\"/><path vector-effect=\"non-scaling-stroke\" d=\"M2.4 12H5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M19 12H21.6\"/></svg>",
    close: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M6 6 18 18\"/><path vector-effect=\"non-scaling-stroke\" d=\"M18 6 6 18\"/></svg>",
    now: "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\"><path d=\"M8 5 8 19 18 12Z\"/></svg>",
    caret: "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M6 9 12 15 18 9\"/></svg>",
    danger: "<svg viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M12 4 21 20H3Z\"/></svg>",
};
// Saved favourite: the plus mark in gold with a heavier stroke.
const MR_ICON_STAR_SAVED = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\"><path vector-effect=\"non-scaling-stroke\" d=\"M12 5.5V18.5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M5.5 12H18.5\"/></svg>";
const mrIcon = key => MR_ICON[key] || '';
